### ISSUE TITLE
Authentication questions

### ISSUE THREAD

**Issue by conman124** [byu-oit/android-byu-suite-v2#431]
Hi,

I have a few questions.  First, it seems like the app authentication token is valid even across password changes.  I haven't verified this for sure, but it certainly works a few minutes after a password change.  Is this the case?  If so, is this secure?  It seems like standard advice upon finding out someone else has your password to an account is "change your password", but this wouldn't affect the app, at least as far as I can tell.

Second, it seems like the app goes against something in the BYU developer documentation \([here](https://developer.byu.edu/docs/consume-api/use-api/choose-grant-type/resource-owner-password-credentials-grant-type)\) where it says that the `Resource Owner Password Credentials grant type` should not be used in production applications.  As near as I can tell, this is how it is implemented in the app.  Is this just an exception to that rule?

**Comment by romrell4** [comment]
conman124,

Thanks for your questions. Hopefully I can help answer some of the concerns you have.

As for the OAuth token: The app's authentication will not persist across password changes. It is true that a token obtained with the valid username and password will continue to work for the rest of the validity of the token (which is currently an hour at maximum). However, I think there is a disconnect with the understanding of OAuth. The OAuth token should be thoughts of as separate from your username and password. You use your username and password to register for the token, but then you "authorize" the mobile app to access your BYU data. If you ever wanted to "unauthorize" the app from accessing your data, WSO2 should have a page that will do that. So, in summary, when changing your password, the token will continue to work until it's expired (much like a cookie on a browser will continue to work after a password change). However, the real way to unauthorize that token is through WSO2.

To answer your second question, the line in the BYU developer documentation was actually placed there because of the experience we have had with the BYU app. We were the first ones to try using OAuth through BYU's API manager, and the password grant type seemed the easiest option. At that point, it actually seemed like the only option due to limitations presented by WSO2. It was implemented about 6 months ago, and things have gone fairly well for that time. However, when using the password grant type, we have noticed that the username/password verification process sometimes has down-time, which causes users not to be able to obtain access tokens. For this reason, BYU has decided to move away from password grant type in production applications. The mobile app is now starting a migration to use another grant type, which will be much more supported, and hopefully have less down time. There are no security concerns involved, but for better user experience and functionality, password grant types are no longer encouraged for production applications.

Does that help answer your questions? If not, feel free to ping me back, or reach our feedback channel at android_team@byu.edu
